export const Strings = {
    getstartdescription:'Take a moment each day to ready \n positive and inspiring quotes \n and rewire your brain to reward \n optimism.',
    getstart:'Get Started',
    getstarttxt:'This app has helped me get through so many \n tough times',
    whatsname:'What is your name ?',
    yourname:'Your Name',
    continue:'Continue',
    skipnow:'Skip for now',
    identity:'Which is your current \n gender identity?',
    prefernot:'Prefer not to say',
    setreminder:'Set daily Motivation \n Reminders.',
    widgets1:'Add a widget to your \n home screen',
    widgets2:'Once added, you can configure \n them from the app.',
    howmany:'How many',
    startat:'Start at',
    endat:'End at',
    sound:'Sound',
    feeling1:'How are you feeling lately?',
    feeling2:'Select the mood that best reflects how \n you feel at this moment.',
    feeling21:'What is making you feel \n that way?',
    feeling22:'You can select more than one option'
}