export const Assets = {
    splash_background : require('../images/splash_background.png'),
    colon:  require('../images/colon.png'),
    reviewimg: require('../images/reviewimg.png'),
    star: require('../images/star.png'),
    profile: require('../images/profile.png'),
    profileicon: require('../images/profileicon.png'),
    rightarrow:require('../images/rightarrow.png'),
    happy:require('../images/happy.png'),
    boy:require('../images/boy.png'),
    girl:require('../images/girl.png'),
    boy_girl: require('../images/boy_girl.png'),
    watch: require('../images/watch.png'),
    circlearrow:require('../images/circlearrow.png'),
    widgets:require('../images/widgets.png'),
    boywithdog:require('../images/boywithdog.png'),
    feeling2:require('../images/feeling2.png'),
    themehead:require('../images/themehead.png'),
    frame814:require('../images/Frame814.png'),
    frame815:require('../images/Frame815.png'),
    frame816:require('../images/Frame816.png'),
    frame817:require('../images/Frame817.png'),
    frame818:require('../images/Frame818.png'),
    frame819:require('../images/Frame819.png'),
    frame820:require('../images/Frame820.png'),
    frame821:require('../images/Frame821.png'),
    frame822:require('../images/Frame822.png'),
    bg1: require("../images/bg1.jpg"),
    bg2: require("../images/bg2.jpg"),
    bg3: require("../images/bg3.jpg"),
    bg4: require("../images/bg4.png"),
    bg5: require("../images/bg5.jpg"),
    bg6: require("../images/bg6.jpg"),
    bg7: require("../images/bg7.jpg"),
    bg8: require("../images/bg8.jpg"),
    bg9: require("../images/bg9.jpg"),
    lifearea:require('../images/lifearea.png'),
}